[deployment]
pattern = "pattern2"
node_act_as = "all"

[traffic_mgr_node]
traffic_publishers="{tcp://tm1.node:9611},{tcp://tm2.node:9611}"

[analytics]
nodes = "{tcp://apimgt.analytics:7611}"
mgt_endpoint = "apimgt.analytics:7444"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database]
type =	"mysql"
hostname = "localhost"
port = 3306
name = "sharedDb"
username = "root"
password = "root"
pool_options = [
    ["maxActive","5"]
]

[gateway]
gateway_environments = ["dev"]
dev.name = "Sandbox" # and Sandbox
dev.type = "hybrid"
dev.display_in_api_console = true
dev.description = "Sandbox"
dev.display_token_endpoint	= true
dev.management_endpoint = "localhost:9443"
dev.http_loadbalance_endpoint	= "api.gateway:80"
dev.https_loadbalance_endpoint =	"api.gateway:443"
dev.ws_loadbalance_endpoint = "api.gateway:9091"
dev.mark_as_revoke_endpoint = true


[store]
mgt_endpoint = "api.store:9443"
