[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[user_store]
type = "database"

[database.shared_db]
type = "h2"
url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"
[database.shared_db.pool_options]
max_active = "50"
max_wait = "60000"
test_on_borrow = true
validation_interval = "30000"
default_auto_commit = true

# To seperate user data
#[database.user]
#type = "h2"
#url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"
#[database.shared_db.pool_options]
#maxActive = "50"
#maxWait = "60000"
#testOnBorrow = true
#validationInterval = "30000"
#defaultAutoCommit = true


# To seperate config data
#[database.config]
#type = "h2"
#url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"
#[database.shared_db.pool_options]
#maxActive = "50"
#maxWait = "60000"
#testOnBorrow = true
#validationInterval = "30000"
#defaultAutoCommit = true

#[config_data]
#path = "/_system/config/apim" to change data path
#enable_cache = true To enable data feched from config

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[keystore.tls]
file_name = "wso2carbon.jks"
type ="JKS"
password ="wso2carbon"
alias ="wso2carbon"
key_password = "wso2carbon"
[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

