[deployment]
hostname = "localhost"

[user_store]
type = "jdbc"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type =	"h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[keystore.tls]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"
