[deployment]
hostname = "wso2.com"
https_port = "9443"       # Mgt console port
local_member_host = "127.0.0.1"
super_admin.username = "admin"      
super_admin.password = "admin" 

[[datasource]]      # can be multiple, hence an array
id = "WSO2CarbonDB"
type = "h2"     # h2, mysql, postgre, oracle, db2, custom
hostname = "localhost"
port = 3306
database_name = "carbondb"
username = "<user>"
password = "<password>"
db_options.useSSL= true
pool_options.maxActive = 5

[[datasource]]      # can be multiple, hence an array
id = "UserDB"
type = "mysql"     # h2, mysql, postgre, oracle, db2, custom
url = "<connection_url>"
username = "<user>"
password = "<password>"
pool_options.maxActive = 5

[[datasource]]      # can be multiple, hence an array
id = "SharedDB"
type = "custom"     # h2, mysql, postgre, oracle, db2, custom
driver_class= "<Driver Class>" # only if datasource type as custom
url = "<connection_url>"
username = "<user>"
password = "<password>"

[user_mgt]
create_super_admin = true
role_to_assign_by_default = "everyone"
property.ABC=""
datasource = "UserDB"

[user_mgt.userstore]
type = "read_write_ldap"  # read_only_ldap, active_directory, jdbc
read_write_ldap.ConnectionURL = ""
read_write_ldap.ConnectionName = ""
read_write_ldap.ConnectionPassword = ""
read_write_ldap.UserSearchBase = ""
read_write_ldap.GroupSearchBase = ""

[user_mgt.authorization_mgt]
property.AuthorizationCacheEnabled = true
property.GetAllRolesOfUserEnabled = false

[clustering] # optional
membershipScheme = "wka"
domain = "wso2.carbon.domain"
mcastAddress = "${deployement.local_member_host}"
mcastPort = 45564
mcastTTL = 100
mcastTimeout = 60
local_member_host = "${deployement.local_member_host}"
local_member_port = 4000

[[clustering.member]] # optional
hostName= "${deployement.local_member_host}"
port= 4000

[shared_registry]
datasource = "SharedDB"

[shared_registry.config] # optional
id = "gov"
mount.path = "/_system/config"
mount.targetPath = "/_system/config"

[shared_registry.governance] # optional
id = "gov"
mount.path = "/_system/governance"
mount.targetPath = "/_system/governance"

[[shared_registry.remote_instance]] # optional
id = "gov"
url = ""
cache_id = ""
datasource = "SharedDB"
read_only = false
enable_cache = true
registry_root = "/"

[[keystore]]
id = "carbon"
path = "<path>"
password = "<password>"
alias = ""
key_password = ""

[truststore]
id = "truststore"
path = "<path>"
password = "<password>"
