# Refer values within the file - ${section::key}
# Refer environment variables - $env{key}
# Refer system variables - $sys{key}
# Refer securevault variables - $sec{key}

[deployment]                    # Deployment related configuration
hostname = "config.wso2.com"        # Public host name, If an LB is present this will be the LB's public hostname
transports = ["https","http"]       # 1st is considered default. Refer transport section for additional properties
local_member_host = "127.0.0.1"     # Internal Hostname/IP of the node itself.
proxy_context_path = ""             # Relative Context to URl Generation
super_admin.username = "admin"      # Super admin's credentials
super_admin.password = "admin"


[tenant_mgt]
tenant_idle_timeout = 30  # Idle Timeout for tenants
eager_loading_tenants = "" # tenant regex to load tenants at server startup
enable_email_domain = true

[tenant_mgt.tenant_manager]
class = "org.wso2.carbon.user.core.tenant.JDBCTenantManager"
config_builder = "org.wso2.carbon.user.core.config.multitenancy.CommonLDAPRealmConfigBuilder"
root_partition = "dc=wso2,dc=org"
organizational_object_class = "organizationalUnit"
organizational_attribute = "ou"
organizational_subcontext_object_class = "organizationalUnit"
organizational_subcontext_attribute = "ou"


[[datasource]]              # Configuration for DBs, Can be multiple if multiple DBs are used.
id = "WSO2CarbonDB"
type = "h2"                 # Can be h2, mysql, postgre, oracle, db2, custom
hostname = "localhost"
port = 3306
database_name = "carbondb"
username = "<user>"
password = "<password>"
db_options = [              # Will be a n * 2 array which will contain 'n' key,value pairs.
    ["useSSL","true"]
]
pool_options = [
    ["maxActive","5"]
]

[[datasource]]
id = "UserDB"
type = "mysql"
url = "<connection_url>"
username = "<user>"
password = "<password>"
pool_options = [
    ["maxActive","5"]
]

[[datasource]]
id = "SharedDB"
type = "custom"     # h2, mysql, postgre, oracle, db2, custom
driver_class= "<Driver Class>" # only if datasource type as custom
url = "<connection_url>"
username = "<user>"
password = "<password>"


[user_mgt]
create_super_admin = true               # Whether to attempt creating super admin user.
role_to_assign_by_default = "everyone"  # Role name that will get assigned for all the users created
properties = [                          # Custom datasource properties if required
    ["property1","value1"],
    ["property2","value2"]
]
datasource = "UserDB"                   # Data source to be used for internal user mgt purposes

[user_mgt.userstore]
username_attribute = "username"         # username, email
type = "read_write_ldap"                # read_only_ldap, active_directory, jdbc
read_write_ldap.connection_uRL = ""
read_write_ldap.connection_name = ""
read_write_ldap.connection_password = ""
read_write_ldap.user_search_base = ""
read_write_ldap.group_search_base = ""

[user_mgt.authorization_mgt]            # Userstore's authorization related properties
properties = [
    ["AuthorizationCacheEnabled", "true"],
    ["GetAllRolesOfUserEnabled", "false"]
]


[clustering] # optional
membershipScheme = "wka"
domain = "wso2.carbon.domain"
mcastAddress = "${deployement::local_member_host}"
mcastPort = 45564
mcastTTL = 100
mcastTimeout = 60
local_member_host = "${deployement::local_member_host}"
local_member_port = 4000

[[clustering.member]]                   # Local member will be added by default if clustering enabled
hostName= "192.168.1.2"
port= 4000


[shared_registry]
datasource = "SharedDB"

[shared_registry.config] # optional
id = "gov"
mount.path = "/_system/config"
mount.targetPath = "/_system/config"

[shared_registry.governance] # optional
id = "gov"
mount.path = "/_system/governance"
mount.targetPath = "/_system/governance"

[[shared_registry.remote_instance]] # optional
id = "gov"
url = ""
cache_id = ""
datasource = "SharedDB"
read_only = false
enable_cache = true
registry_root = "/"


[[keystore]]
id = ""
path = ""
password = ""
alias = ""
key_password = ""


[truststore]
path = ""
password = ""


[data_bridge]
worker_threads = 10
max_event_buffer_capacity = 10
event_buffer_size = 2000
client_timeout_in_minutes = 30

[data_bridge.thrift]
tcp_port = 7611
ssl_port = 771
ssl_enable_protocols = "TLSv1,TLSv1.1,TLSv1.2"
ciphers = "SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA"
tcp_max_worker_threads = 5
tcp_min_worker_threads = 2
tcp_request_timeout = 15
tcp_stop_timeout = 15
ssl_max_worker_threads = 5
ssl_min_worker_threads = 2
ssl_request_timeout = 15
ssl_stop_timeout = 50

[data_bridge.binary]
tcp_port = 9611
ssl_port = 9711
ssl_receiver_thread_pool_size = 100
tcp_receiver_thread_pool_size = 100
ssl_enable_protocols = "TLSv1,TLSv1.1,TLSv1.2"
ciphers = "SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA"


[[data_agent]]
type = binary # binary,thrift
queue_size = 32768
batch_sise = 200
core_pool_size = 1
socket_timout_millis = 30000
max_pool_size = 1
keep_alive_time = 20
re_connection_interval = 30
max_transport_pool_size = 250
max_idle_connection = 250
eviction_time_period = 5500
min_idle_time = 5000
secure_max_transport_pool_size = 250
secure_max_idle_connections = 250
secure_eviction_time_period = 5500
secure_min_idle_time_in_pool = 5000
ssl_enable_protocols = "TLSv1,TLSv1.1,TLSv1.2"
ciphers = "SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA"


[jmx]
enable = true
hostname = "localhost"

[transport.http]
port = "9763"
proxy_port = "80"
redirect_port = "9443"
max_http_header_size = "8192"
acceptor_thread_count = "2"
max_threads = "250"
min_spare_threads = "50"
disable_upload_time_out = "false"
connection_upload_time_out ="120000"
max_keep_alive_requests = "200"
accept_count = "200"
server = "WSO2 Carbon Server"
compression = "on"
compression_min_size = "2048"
no_compression_user_agents = "gozilla, traviata"
compressable_mime_type = "text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
uri_encoding = "UTF-8"

[transport.https]
port = "9443"
ssl_protocol = "TLS"
ssl_enabled_protocol = "TLSv1,TLSv1.1,TLSv1.2"
max_http_header_size = "8192"
acceptor_thread_count = "2"
max_threads = "250"
min_spare_threads = "50"
disable_upload_time_out = "false"
enable_lookups = "false"
connection_upload_time_out = "120000"
max_keep_alive_requests = "200"
accept_count = "200"
server = "WSO2 Carbon Server"
client_auth = "false"
compression = "on"
compression_min_size = "2048"
no_compression_user_agents = "gozilla, traviata"
compressable_mime_type = "text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
uri_encoding = "UTF-8"
