# Refer values within the file - ${section::key}
# Refer environment variables - $env{key}
# Refer system variables - $sys{key}
# Refer securevault variables - $sec{key}

[deployment]                    # Deployment related configuration
hostname = "config.wso2.com"        # Public host name, If an LB is present this will be the LB's public hostname
local_host_name = "127.0.0.1"     # Internal Hostname/IP of the node itself.
proxy_context_path = ""             # Relative Context to URl Generation
create_super_admin = true               # Whether to attempt creating super admin user.
super_admin.username = "admin"      # Super admin's credentials
super_admin.password = "admin"

# Shared database of the server. 
[database]
type = "mysql"
hostname = "localhost"
port = 3306
name = "UserDB"
username = "<user>"
password = "<password>"
pool_options = [
    ["maxActive","5"]
]

[tenant_mgt]
tenant_idle_timeout = 30  # Idle Timeout for tenants
eager_loading_tenants = "" # tenant regex to load tenants at server startup
enable_email_domain = true

[tenant_mgt.tenant_manager]
type  = "jdbc" # jdbc , ldap , custom
class = "<custom Tenant Manager>"
config_builder = "<custom config builder>"
root_partition = "dc=wso2,dc=org"
organizational_object_class = "organizationalUnit"
organizational_attribute = "ou"
organizational_subcontext_object_class = "organizationalUnit"
organizational_subcontext_attribute = "ou"


[user_mgt]
role_to_assign_by_default = "everyone"  # Role name that will get assigned for all the users created
properties = [                          # Custom datasource properties if required
    ["property1","value1"],
    ["property2","value2"]
]

database.type = "mysql"
database.hostname = "localhost"
database.port = 3306
database.name = "UserDB"
database.username = "<user>"
database.password = "<password>"
database.pool_options = [
    ["maxActive","5"]
]
authorization_mgt.properties = [
    ["AuthorizationCacheEnabled", "true"],
    ["GetAllRolesOfUserEnabled", "false"]
]


[user_mgt.userstore]
user_identifier_attribute = "username"         # username, email
type = "jdbc"                                  # read_only_ldap, active_directory, jdbc
# For IS, the default configuration will be as follows
# type = "read_write_ldap"
# read_write_ldap.connection_url = ""
# read_write_ldap.connection_name = ""
# read_write_ldap.connection_password = ""
# read_write_ldap.user_search_base = ""
# read_write_ldap.group_search_base = ""


[clustering] # optional
membershipScheme = "wka"
domain = "wso2.carbon.domain"
local_member_host = "${deployement::local_host_name}"
local_member_port = 4000
members = [ "192.168.1.2:4000", "192.168.1.2:4000" ]

[[keystore]]
id = ""
path = ""
password = ""
alias = ""
key_password = ""


[truststore]
path = ""
password = ""


[[data-publisher]]
type = binary # binary,thrift
queue_size = 32768
batch_sise = 200
core_pool_size = 1
socket_timout_millis = 30000
max_pool_size = 1
keep_alive_time = 20
re_connection_interval = 30
max_transport_pool_size = 250
max_idle_connection = 250
eviction_time_period = 5500
min_idle_time = 5000
secure_max_transport_pool_size = 250
secure_max_idle_connections = 250
secure_eviction_time_period = 5500
secure_min_idle_time_in_pool = 5000
ssl_enable_protocols = "TLSv1,TLSv1.1,TLSv1.2"
ciphers = "SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA"


[monitoring]
enable = true
hostname = "localhost"

[transport.http]
port = "9763"
proxy_port = "80"
redirect_port = "9443"
max_http_header_size = "8192"
acceptor_thread_count = "2"
max_threads = "250"
min_spare_threads = "50"
disable_upload_time_out = "false"
connection_upload_time_out ="120000"
max_keep_alive_requests = "200"
accept_count = "200"
server = "WSO2 Carbon Server"
compression = "on"
compression_min_size = "2048"
no_compression_user_agents = "gozilla, traviata"
compressable_mime_type = "text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
uri_encoding = "UTF-8"

[transport.https]
port = "9443"
ssl_protocol = "TLS"
ssl_enabled_protocol = "TLSv1,TLSv1.1,TLSv1.2"
max_http_header_size = "8192"
acceptor_thread_count = "2"
max_threads = "250"
min_spare_threads = "50"
disable_upload_time_out = "false"
enable_lookups = "false"
connection_upload_time_out = "120000"
max_keep_alive_requests = "200"
accept_count = "200"
server = "WSO2 Carbon Server"
client_auth = "false"
compression = "on"
compression_min_size = "2048"
no_compression_user_agents = "gozilla, traviata"
compressable_mime_type = "text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
uri_encoding = "UTF-8"