[deployment]
pattern = "pattern3"
node_act_as = "gateway"

[key_mgr_node]
endpoints = "km.wso2:9443"

[traffic_mgr_node]
traffic_publishers="{tcp://tm1.node:9611}"
throttle_decision_endpoints=["tm1.node:5672"]

[analytics]
nodes = "{tcp://localhost:7611}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true
