[deployment]
pattern = "pattern3"
node_act_as = "publisher"

[traffic_manager]
traffic_publishers="{tcp://tm1.node:9611}"
throttle_decision_endpoints=["tm1.node:5672"]
mgt_endpoint = "tm.wso2.com:9443"

[analytics]
nodes =	"{tcp://localhost:7611}"
load_balance_endpointk = "apimgt.analytics:7444"


[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database]
type = "mysql"
hostname = "localhost"
port = 3306
name = "sharedDb"
username = "root"
password = "root"
pool_options = [
  ["maxActive","5"]
]

[gateway]
gateway_environments=["dev"]
dev.name = "Sandbox"
dev.type = "hybrid"
dev.display_in_api_console = true
dev.description = "Sandbox"
dev.isDefault = true
dev.management_endpoint = "mgt.gateway:443"

[store]
load_balance_endpoiint = "api.store:9443"
