[deployment]
pattern	= "pattern3"
node_act_as	= "store"
key_manager.url = "apim.km:9443"

[analytics]
nodes	= "{tcp://localhost:7611}"
load_balanace_endpoint = "apimgt.analytics:7444"


[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database]
type = "mysql"
hostname = "localhost"
port = 3306
name = "sharedDb"
username = "root"
password = "root"
pool_options = [
  ["maxActive","5"]
]

[gateway]
gateway_environments = ["dev"]
dev.name = "Sandbox" # and Sandbox
dev.type = "hybrid"
dev.display_in_api_console = true
dev.description = "Sandbox"
dev.isDefault	= true
dev.management_endpoint = "mgt.gateway:443"
dev.http_loadbalance_endpoint	= "api.gateway:80"
dev.https_loadbalance_endpoint =	"api.gateway:443"
dev.ws_loadbalance_endpoint = "api.gateway:9091"
dev.mark_as_revoke_endpoint = true
