# Start of identity configuration

[identity]
datasource = "jdbc/SharedDB"


[identity.session.timeout]
idle_session_timeout_mins = 15
remember_me_session_timeout_mins = 20160


[identity.authentication]
prompt_user_consent = true  # Applies to non oidc protocols


[[identity.authentication.authenticator]]
name = ""
alias = ""
parameters = [
    ["AuthMechanism","basic"]
]

[identity.authentication.adaptive]
event_publisher.url = ""
event_publisher.authentication = "basic"    # none, basic
event_publisher.authentication.basic.username = "admin"
event_publisher.authentication.basic.password = "admin"


[identity.oauth]
token.cleanup.enable = true
token.cleanup.backup_for_auditing = true
app_token.validity_time_s = 3600
user_token.validity_time_s = 3600
refresh_token.validity_time_s = 3600
authz_code.validity_time_s = 300
hash_client_secret = false

[identity.oauth.oidc]
prompt_user_consent = true  # eq. skipConsent = false

[[identity.oauth.oidc.request_object_builder]]
type = "request_param_value_builder"
class = ""     # Optional for OOTB builders

[[identity.oauth.response_type]]
name = "token"
handler_class = ""    # Optional for default response_types

[[identity.oauth.response_type]]
name = "code"
handler_class = ""

[[identity.oauth.response_type]]
name = "id_token"
handler_class = ""

[[identity.oauth.response_type]]
name = "id_token token"
handler_class = ""

[[identity.oauth.grant_type]]
name = "authorization_code"
handler_class = ""

[[identity.oauth.grant_type]]
name = "password"
handler_class = ""

[[identity.oauth.grant_type]]
name = "refresh_token"
handler_class = ""

[[identity.oauth.grant_type]]
name = "client_credentials"
handler_class = ""

[[identity.oauth.grant_type]]
name = "urn:ietf:params:oauth:grant-type:saml2-bearer"
handler_class = ""
properties = [
    ["user_type","FEDERATED"]    # from SAML2Grant.UserType
]

[[identity.oauth.grant_type]]
name = "iwa:ntlm"
handler_class = ""

[[identity.oauth.grant_type]]
name = "urn:ietf:params:oauth:grant-type:jwt-bearer"
handler_class = ""
validator_class = ""      # Optional

[[identity.oauth.callback_handler]]
name = "default"
class = ""

[[identity.oauth.token_validator]]
name = "jwt"    # represent the old attribute 'type'
class = ""    # Optional for OOTB validators

[[identity.oauth.scope_validator]]
name = "jdbc"
class = ""    # Optional for OOTB validators

[[identity.oauth.scope_handler]]
name = "oidc"
class = ""    # Optional for OOTB handlers

[identity.mgt.recovery]
notification.manage_internally = true
notification.notify_success = false
endpoint.enable = true
username_recovery.recaptcha.enable = true
username_recovery.with_notification.enable = true
password_recovery.recaptcha.enable = true
password_recovery.with_notification.enable = true
password_recovery.with_challenge_question.enable = true
password_recovery.with_challenge_question.notify_start = true
password_recovery.with_challenge_question.separator_char = true
password_recovery.with_challenge_question.min_answers = 2
password_recovery.with_challenge_question.recaptcha.enable = true
password_recovery.with_challenge_question.recaptcha.max_fails = 2
password_recovery.by_admin.offline = false
password_recovery.by_admin.otp = false
password_recovery.by_admin.recovery_link = false

[identity.mgt.email_verification]
account.lock_on_creation = true
notification.manage_internally = true
notification.expiry_time_minutes = 1440
ask_password.expiry_time_minutes = 1440
ask_password.password_generator = ""
ask_password.admin_console_ui.enable = true
check_account_existance = true      # TODO. Need this configurable?

[identity.mgt.self_registration]
endpoint.enable = true
account.lock_on_creation = true
notification.manage_internally = true
notification.expiry_time_minutes = 1440
recaptcha.enable = true


[identity.jit_provisioning]
username.page = ""
password.page = ""


[[identity.event.listener]]
id = ""
type = ""
name = ""
order = 1

[[identity.event.recorder]]
id = ""
type = ""   # eg. user_delete
class = ""
property.abc = ""


# The default caches are enabled by default with default values. Can be disabled/change default config or add a new
# cache here.
[[identity.cache_manager.cache]]
name = ""
timeout = ""
capacity = ""
distributed = false


[[identity.protected.resource]]
context = ""
secured = true
http-method = "all"
permissions = []


[[identity.client_app.authentication]]
name = ""
hash = ""


[identity.user.association]
enable_for_federated_users = false


[identity.tenanat_context.rewrite]
webapps = []
servlets = []


[identity.intermediate_cert_validation]
cert_cns = []
exempt_contexts = []


[identity.google_recaptcha]
api.url = "https://www.google.com/recaptcha/api.js"
verify.url= "https://www.google.com/recaptcha/api/siteverify"
site.key="6LeL8iATAAAAABEWUx1LwFAiSCT06fY7Kfra5WcT"
secret.key="6LeL8iATAAAAAJUgXu_ZgEm_dOC3AT4gmWRstil4"

[identity.embedded_ldap]
ldap.properties = [[]]
default_partition.properties = [[]]
partition_admin.properties = [[]]
partition_admin_group.properties = [[]]
kdc_server.properties = [[]]
