[[datasource]]                      # can be multiple, hence an array
    jndi_name = "jdbc/WSO2CarbonDB"
    type = "h2"                     # h2, mysql, postgre, oracle, db2
    url = ""
    username = ""
    password = ""

[deployement]
    hostname = "wso2is.com"
    super_admin.username = ""      
    super_admin.password = "" 

[userstore]
    type = "read_write_ldap"        # read_only_ldap, active_directory, jdbc   
    ldap.url = ""                   # only for non jdbc
    ldap.username = ""              # only for non jdbc
    ldap.password = ""              # only for non jdbc
    ldap.user_search_base = ""      # only for non jdbc
    ldap.group_search_base = ""     # only for non jdbc        

[[keystore]]
    id = "ssl"
    path = ""
    password = ""
    alias = ""

 [[keystore]]
    id = "carbon"
    path = ""
    password = ""
    alias = ""
    